### PR TITLE
Add import from FranceData

### PR DESCRIPTION
**Pull request by njoyard**
Note: depends on django-representatives v0.0.15 (hence the temporary commit https://github.com/njoyard/django-representatives-votes/commit/2eb01d62ebc62e2815eb5e75503437749342de3f), so https://github.com/political-memory/django-representatives/pull/18 should be merged before this one.

Todo:
* [x] Handle multiple chambers correctly
* [x] ~~Make vote/proposal updates atomic (vote updates + proposal totals recounts should be done in a single transaction)~~ non-issue
* [x] Bump version number

About atomicity, the problem is that JSON input for votes is not sorted. Possible solutions:
1. Make the whole vote update operation one transaction (probably overkill)
2. Sort votes by proposal before processing (requires loading everything in memory, also seems overkill to me)
3. Change FranceData in order to group votes by proposal or at least ensure they're ordered
4. Decide that this is a non-issue

### CODE REVIEW

**Comment by njoyard** [comment]
Updated to handle chambers correctly, import latest schema format from francedata, deduplicate dossiers from AN/Senate.

@jpic what's your POV about the atomicity issue ?

**Comment by njoyard** [comment]
And rebased on master :)

**Comment by jpic** [comment]
Nice !

If I understand correctly, you mean that votes may be only partially imported for a Proposal ie. if the import process is killed. I don't think it's an issue really, because if that happens then the first thing you want to do is fix the issue and re-run the script.

Do you think it would be possible to do single-dossier sync like on parltrack ? It's used by political-memory/political_memory#56

**Comment by njoyard** [comment]
That was my point of view about atomicity, too, but I asked because parltrack scripts do it atomically (which is easier for them as the proposal json contains votes).

Single dossier sync would be possible if FranceData gave access to single dossier jsons. I was thinking of reworking the scrapers to output data in separate files for that, but currently it has no real sense.

**Comment by njoyard** [comment]
Depends on https://github.com/political-memory/django-representatives/pull/18 to be able to remove temp commit https://github.com/njoyard/django-representatives-votes/commit/2eb01d62ebc62e2815eb5e75503437749342de3f

**Comment by njoyard** [comment]
Ready for merge :+1:

**Comment by jpic** [comment]
:guitar:

**Pull request merged**
