### PR TITLE
Add single dossier sync from parltrack

### PR DESCRIPTION
**Pull request by njoyard**
This is basically a rewrite of #8 without unrelated architecture changes.

I tried to keep the changes as light as possible to go straight to the point. The main highlights in this PR:
- `contrib.parltrack.import_dossiers` now has a `import_single(stream)` function to import a single dossier in JSON format, and a `sync_dossier(reference)` function to sync a dossier from its reference (downloads the JSON from parltrack, and runs import_single).
- Importing dossiers in `contrib.parltrack` now uses the `votes` key in a dossier to update votes when applicable. This does not impact bulk dossier updates as dossier dumps don't have votes in them, and allows vote updates when using single-dossier JSONs.
- ~~Dossiers now have a new `parltrack_sync(refresh=False)` method to trigger download from parltrack and update dossiers and votes. The refresh argument toggles calling `self.refresh_from_db()` after sync~~ *not anymore since 1dec52b*
- The PR introduces `assertNumQueries` calls in parltrack tests. As what I've done merely plugs into existing code, I just ran the test once to check the number of queries executed and put that in the test suite ; no optimization of any sort was done. 

Caveats:
- ~~The app now has a dependency with `contrib.parltrack` (through `models.py:Dossier.parltrack_sync`) ; in case this is unwanted maybe we should stick to using `contrib.parltrack.import_dossiers.sync_dossier(reference)` directly?~~ *not anymore since 1dec52b*
- ~~The API for `Dossier.parltrack_sync` may not be perfect as I may not have all possible use cases in mind~~ *not anymore since 1dec52b*
- ~~CI test results now depend on parltrack website availability for downloading a JSON dossier file. I plan to add a mechanism to switch between parltrack and a stub but that belongs in a future PR.~~ *not anymore since 4e3fef7*
- Existing tests should be rewritten to call `assertNumQueries`. That belongs in a future PR, too.

### CODE REVIEW

**Comment by jpic** [comment]
> The app now has a dependency with contrib.parltrack (through models.py:Dossier.parltrack_sync) ; in case this is unwanted maybe we should stick to using contrib.parltrack.import_dossiers.sync_dossier(reference) directly?

Absolutely !

> The API for Dossier.parltrack_sync may not be perfect as I may not have all possible use cases in mind

In reality, we have one use case: we want a cron command to synchronize all Proposal votes which have a [Recommendation](https://github.com/political-memory/political_memory/pull/47/files#diff-15f8c7e16c5b9c5f6dbb51133076754aR20). It doesn't matter if we sync extra proposals for now, even though it would be nice to be able to sync only those proposals (from memopol): `Proposal.objects.exclude(Recommendation=None)`

**Comment by njoyard** [comment]
Didn't you want to be able to sync individual proposals when edited by an admin, too?

**Comment by jpic** [comment]
On Mon, Jan 4, 2016 at 10:42 AM, Nicolas Joyard <notifications@github.com>
wrote:

> Didn't you want to be able to sync individual proposals when edited by an
> admin, too?
>
True, but what's the difference if we have a cron running every 5 or 10
minutes for this ?

KISS ;)

**Comment by njoyard** [comment]
Okay, I'll make some changes to this PR tonight then !

**Comment by njoyard** [comment]
I think this PR is in pretty good shape now, what do you think?

**Comment by Psycojoker** [comment]
Looks good from here.

**Comment by jpic** [comment]
Merged from #14

**Comment by jpic** [comment]
Thanksssssssssssssssssssssssssssssssssssssssssssss :guitar:

**Pull request closed without merging**
